import { Marcellus, Montserrat } from "next/font/google";
import "./globals.css";

import CursorContextProvider from "@/components/CursorContext";
// components
import Transition from "@/components/Transition";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";

const marcellus = Marcellus({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-marcellus",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={`${marcellus.variable} ${montserrat.variable} overflow-x-hidden`}
      >
        <CursorContextProvider>
          <Transition />
          <Header />
          <PageTransition />
          {children}
        </CursorContextProvider>
      </body>
    </html>
  );
}
